service: practice

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb
    
Type: AWS::S3::BucketPolicy
Properties: 
  Bucket: String
  PolicyDocument: Json
